services:
  db:
    image: mysql:8.0
    container_name: usac_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usac_reviews
      TZ: America/Guatemala
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docs:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: ./server
    container_name: usac_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: usac_reviews
      JWT_SECRET: supersecret
      FRONTEND_URL: http://localhost:5173
      EMAIL_FROM: no-reply@example.com
      TZ: America/Guatemala
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ./client
    container_name: usac_web
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  db_data:
